### ISSUE TITLE
Differences from smoochbot project

### ISSUE THREAD

**Issue by facultymatt** [smooch/smooch-bot#11]
How is this project different from: https://github.com/gozman/smoochbot

If there an official package from smooch ?

**Comment by alavers** [comment]
https://github.com/gozman/smoochbot brings Smooch support to BotKit (howdyai/botkit)

https://github.com/alavers/smooch-bot however is its own node.js bot framework (http://blog.smooch.io/how-to-build-your-own-smooch-bot/) This framework is a very small starting point, intended to give you full control over how you want your bot to behave, meaning it's incomplete, you have to write code to fill in the specifics. Neither project is officially supported by Smooch :)

However, Smooch does officially support integrations with 3rd party bot frameworks that are much more rich in terms of features. You can already use [Meya.ai](https://meya.ai/) with Smooch now, and support for many other bot frameworks will be announced very soon in the coming weeks.
