### ISSUE TITLE
How to move Bot to a session from one Script step to the next.

### ISSUE THREAD

**Issue by qadir-genetech** [smooch/smooch-bot#17]
From Docs 
`StateMachine: This is the engine that uses the Bot to guide a session from one Script step to the next.`

I have two scenarios.
1. Simply I have to move Bot from one Script step to the next step's **PROMPT** function.
2. I have to move Bot from one Script step to the next step's **RECEIVE** function with some params passed in

to handle this I have done like below.

```
function handleChangeStateMachine(stateMachine, res, ai_action, params){

    console.log("Change state to => "+ ai_action + " Prompt " + params.should_prompt);

    if(params.should_prompt == "true"){

        console.log("IF Prompt " + params.should_prompt);
        // Scenario 1
        Promise.all([
            stateMachine.bot.releaseLock(),
            stateMachine.setState(ai_action),   // set new state
            stateMachine.prompt(ai_action)      // goto prompt
        ]);
        res.end();

    }else{

        console.log("ELSE Prompt " + params.should_prompt);
        // Scenario 2
        Promise.all([
            stateMachine.bot.releaseLock(),
            stateMachine.setState(ai_action),   // set new state
            stateMachine.receiveMessage(params) // goto receiveMessage
        ]);
        res.end(); 
    }
}
```

**QUESTION(s):**
1. Is this correct way? Please mention other method if any.

**PROBLEM(s):**
1. I am facing issue sometimes in my 2nd scenario (sometimes it works perfectly)
problem is that my bot is not moving to next step's receiveMessage() function but it remains in the previous state and my params passed in previous state. Hence my bot doesn't respond correctly.

**Comment by qadir-genetech** [comment]
@alavers any comment?

**Comment by alavers** [comment]
Oh boy. :|

I don't think I quite understand your scenarios as described, but just looking at the code there are a few problems:

`Promise.all` doesn't block. In both scenarios `res.end()` happens before any of your stateMachine operations finish. If this was intended, then there' s no need for the `Promise.all`, you can just call each  `stateMachine.*` directly, they're asynchronous.

If you expect that stuff to happen before responding to the web request, then maybe that's what's causing your problem? I'm really not sure.

Not sure why `releaseLock` is being called. Are you acquiring a lock at some point earlier?

Scenario 2 doesn't make too much sense since `stateMachine.receiveMessage` takes care of setting the state already.

**Comment by qadir-genetech** [comment]
OK. I have removed `releaseLock` and removed Promise.all too. its working now.
but I am getting error in my following state

```
DO_NOTHING:{

        receive: (bot, message) => {
            
            console.log("DO_NOTHING message : "+ JSON.stringify(message));
            var user_said = (message.text == undefined) ? message : message.text

            return 'DO_NOTHING'
        }
    },
```

here is the error log

```
DO_NOTHING message : {"food_categories":"pasta","guest-feelings":"","should_prompt":"false"} 
Jul 20 01:51:59 qjamesbot-staging app/web.1: (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Conflict 
```

I am unable to debug the issue. can you help me to debug.

**Comment by qadir-genetech** [comment]
Finally got full error log. using catch

updated my above method code to 

```
function handleChangeStateMachine(stateMachine, res, ai_action, params){

    console.log("Change state to => "+ ai_action + " Prompt " + params.should_prompt);

    if(params.should_prompt == "true"){

        console.log("IF Prompt " + params.should_prompt);

         stateMachine.setState(ai_action)
        .catch((err) => {
            console.error('SmoochBot error: setState', err);
            res.end();
        });

        stateMachine.prompt(ai_action)
        .then(() => res.end())
        .catch((err) => {
            console.error('SmoochBot error: prompt', err);
            res.end();
        });

    }else{

        console.log("ELSE Prompt " + params.should_prompt);
        
        stateMachine.setState(ai_action)
        .catch((err) => {
            console.error('SmoochBot error: setState', err); // it crashed here, log given below
            res.end();
        });

        stateMachine.receiveMessage(params)
        .then(() => res.end())
        .catch((err) => {
            console.error('SmoochBot error: receiveMessage', err);
            res.end();
        });
      

    }
}
```

Here is the full log


Jul 20 05:07:37 qjamesbot-staging app/web.1: **SmoochBot error: setState { Error: Conflict** 
Jul 20 05:07:37 qjamesbot-staging app/web.1:     at handleStatus (/app/node_modules/smooch-bot/node_modules/smooch-core/lib/utils/http.js:45:17) 
Jul 20 05:07:37 qjamesbot-staging app/web.1:     at process._tickCallback (internal/process/next_tick.js:109:7) 
Jul 20 05:07:37 qjamesbot-staging app/web.1:   response:  
Jul 20 05:07:37 qjamesbot-staging app/web.1:    Body { 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      url: 'https://api.smooch.io/v1/appusers/9e104f8503723d3b467bbb12', 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      status: 409, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      statusText: 'Conflict', 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      headers: Headers { _headers: [Object] }, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      ok: false, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      body:  
Jul 20 05:07:37 qjamesbot-staging app/web.1:       PassThrough { 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         _readableState: [Object], 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         readable: true, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         domain: null, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         _events: [Object], 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         _eventsCount: 1, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         _maxListeners: undefined, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         _writableState: [Object], 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         writable: false, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         allowHalfOpen: true, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:         _transformState: [Object] }, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      bodyUsed: false, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      size: 0, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      timeout: 0, 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      _raw: [], 
Jul 20 05:07:37 qjamesbot-staging app/web.1:      _abort: false } } 

I don't have any idea whats causing this. 
@alavers any clue please, is this smooch server issue?

**Comment by qadir-genetech** [comment]
Yes, looks my suspect was true.

setState(); is taking some time to be completed and hence recieveMessage() was called before setState() function completed.

I modified the code like below 

What I did is, made a 2 sec delay and then call the recieveMessage() function.

```
function changeStateToReceive(stateMachine, res, ai_action, params, callback){

    changeState(stateMachine, res, ai_action, function(){

        stateMachine.receiveMessage(params)
            .then(() => res.end())
            .catch((err) => {
                console.error('SmoochBot error: receiveMessage', err);
                res.end();
        });
    })
}

```

here is my `changeState` function.

```
function changeState(stateMachine, res, ai_action, callback){

    console.log("changeState called");
    stateMachine.setState(ai_action)
    .catch((err) => {
        console.error('SmoochBot error: changeState', err);
        res.end();
    });

    setTimeout(function(){
        // 2 sec delay because there is no any callback in setState() method
        console.log("changeState callback called");
        callback()
    }, 2 * 1000);
}
```

@alavers isn't better there should be a callback in your setState() function.

**Comment by alavers** [comment]
setState doesn't need a callback, it's already returning a promise.

My friend, I don't mean to be rude, asynchronous javascript isn't easy but I'm not about to try teaching it to you in a github issue.

**Comment by qadir-genetech** [comment]
@alavers I just wanted to know how to change state from one to another. thats it. Above code without delay was not working fine why.
