### ISSUE TITLE
bot.SetProp() inconsistently works

### ISSUE THREAD

**Issue by nacharya114** [smooch/smooch-bot#6]
Whenever I use bot.setProp in my Script, it inconsistently saves the properties I use. It is necessary to retain certain values in the Smooch Store for my bot, but it is also essential that I clear  them out after I use them. When I try to clear them with bot.setProp('property', ""), it only clears out certain properties while other retain their value. This persistence of properties is holding my bot from production.

**Comment by alavers** [comment]
Thanks for reporting @nacharya114 it's fixed. `npm update smooch-bot` and you should be all set.
