### ISSUE TITLE
Is there a way to receive message on the local computer?

### ISSUE THREAD

**Issue by ildella** [smooch/smooch-bot#9]
Hi, 

When I was coding bot with Slack + BotKit I could receive messages on the bot running locally on my machine. That was very handy. 

IS this possible in some way with this new smooch-bot implementation? I guess this old one https://github.com/gozman/smoochbot based on botkit is deprecated?  

Thanks.

**Comment by alavers** [comment]
Yes, you can run your bot script locally. See the console example in the readme here: https://github.com/smooch/smooch-bot-example
